name: mlflow-banknote-env

channels:
  - conda-forge

dependencies:
  - python=3.12.7
  - pip<=24.2

  - pip:
      - mlflow==2.19.0
      - scikit-learn==1.3.2
      - pandas==2.1.4
      - numpy==1.26.4
      - matplotlib==3.8.4
      - joblib==1.4.2
      - cloudpickle==3.0.0
